In [63]:
import sys
sys.path.append("/Users/sandesh/repos/bdg-nanowire/nanowire_model/")
import imp

import physics
imp.reload(physics)

<module 'physics' from '/Users/sandesh/repos/bdg-nanowire/nanowire_model/physics.py'>

In [84]:
my_physics = {}
my_physics['t0'] = 2
my_physics['N_D'] = 10

In [85]:
phy = physics.Physics(my_physics)
phy.create_Hamiltonian()

In [72]:
phy.H.flatten().reshape((4,4,2,2))

array([[[[ 4.,  0.],
         [ 0.,  4.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.]]],


       [[[-2.,  0.],
         [ 0., -2.]],

        [[ 4.,  0.],
         [ 0.,  4.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 4.,  0.],
         [ 0.,  4.]],

        [[-2.,  0.],
         [ 0., -2.]]],


       [[[ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 4.,  0.],
         [ 0.,  4.]]]])

In [32]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = [a]*3

In [33]:
b

[array([[1, 2],
        [3, 4]]), array([[1, 2],
        [3, 4]]), array([[1, 2],
        [3, 4]])]

In [34]:
np.diag(b,dtype=object)

TypeError: diag() got an unexpected keyword argument 'dtype'

In [75]:
phy.H

array([[[[ 4.,  0.],
         [ 0.,  4.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.]]],


       [[[-2.,  0.],
         [ 0., -2.]],

        [[ 4.,  0.],
         [ 0.,  4.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 0.,  0.],
         [ 0.,  0.]]],


       [[[ 0.,  0.],
         [ 0.,  0.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 4.,  0.],
         [ 0.,  4.]],

        [[-2.,  0.],
         [ 0., -2.]]],


       [[[ 0.,  0.],
         [ 0.,  0.]],

        [[ 0.,  0.],
         [ 0.,  0.]],

        [[-2.,  0.],
         [ 0., -2.]],

        [[ 4.,  0.],
         [ 0.,  4.]]]])

In [88]:
np.array([phy.H[x,:,y,:].flatten() for x in range(phy.H.shape[0]) for y in range(phy.H.shape[2])]).flatten().reshape(20,20)

array([[ 4.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  0.,  4.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -2.,  0.,  4.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -2.,  0.,  4.,  0., -2.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.,  0.,  4.,  0., -2.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -2.,  0.,  4.,  0., -2.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -2.,  0.,  4.,  0., -2.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -2.,  0.,  4.,  0., -2.,  